# Generated by Django 6.1.1 on 2026-09-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otprequest_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otprequest',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='otprequest',
            name='channel',
            field=models.CharField(choices=[('phone', 'Phone Number'), ('email', 'Email Address')], default='phone', max_length=10),
        ),
        migrations.AddField(
            model_name='otprequest',
            name='identifier',
            field=models.CharField(db_index=True, default='legacy', max_length=150),
            preserve_default=False,
        ),
    ]
