# Generated by Django 6.1.1 on 2026-09-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_otprequest_phone_number_otprequest_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], default='male', max_length=10),
        ),
    ]
